---
title: "Analyse d'image du zooplancton de Tulear (Madagascar)"
author: "___"
date: "___"
output: html_document
---

<!--# Ceci est un commentaire -->

<!--% Ceci est une consigne. Ne jamais modifier ni déplacer les consignes dans le document ! -->

<!--% Ajoutez la date et votre nom dans l'entête YAML.-->

```{r setup}
SciViews::R(lang = "fr")
```

# Objectif

Analyse graphique du jeu de données `data.io::zooplankton`.

# Analyses graphiques

<!--% Vous importez le jeu de données `zooplankton` depuis le package {data.io} et vous l'assignez à `zoo` ci-dessous (code déjà rempli pour vous). Vous ferez ensuite toutes vos analyses en utilisant `zoo`. -->

```{r importation}
zoo <- read(file = "zooplankton", package = "data.io")
names(zoo)
```

<!--% Réalisez quatre histogrammes pour visualiser la distribution du diamètre du cercle équivalent (`ecd`) en utilisant les nombres de classes suivantes suivantes : 10, 25, 40 et 55, et comparez ces histogrammes entre eux. -->

```{r histo1a}

```

```{r histo1b}

```

```{r histo1c}

```

```{r histo1d}

```

<!--% Parmi les quatre graphiques précédents, sélectionnez celui que vous jugez le plus pertinent et décrivez-le en maximum 3 phrases. Modifiez le nom de l'axe des ordonnées pour le finaliser proprement (count -> Effectifs). -->

```{r histo2}
# Graphique sélectionné et mis au net

```

<!--% Réalisez à présent un graphique de densité pour visualiser la distribution du périmètre (`perimeter`) et décrivez-le en 5 phrases maximum. -->

```{r density}

```

<!--% Réalisez un graphique en violon de l'aire (`area`) par classe (`class`) avec de la couleur pour chaque classe. Assurez-vous que la légende ne soit pas visible sur le graphique et que les classes soient bien lisibles. Décrivez celui-ci en maximum 5 phrases. -->

```{r violin}

```

<!--% Reproduisez le même graphique que le précédent, mais cette fois-ci en utilisant la fonction `ggridges::geom_density_ridges()`. Commentez celui-ci en maximum 5 phrases. -->

```{r density_ridges}
 
```

<!--# `zoo_sub` est une version du jeu de données qui ne contient que les classes suivantes : "Poecilostomatoid", "Calanoid", "Cyclopoid", "Harpacticoid" (uniquement les copépodes). Le code est prérempli pour vous. -->

```{r zoo_sub}
# Réduction du jeu de données zoo
zoo_sub <- sfilter(zoo, class %in% c("Poecilostomatoid", "Calanoid", "Cyclopoid", "Harpacticoid"))
```

<!--% À partir du jeu de données `zoo_sub`, réalisez un histogramme pour visualiser le diamètre de Feret (`feret`) en utilisant un découpage en 25 classes. Créez un graphique en facette avec la classe (`class`). L'histogramme de chaque classe doit être affiché sur un histogramme global grisé représentant l'ensemble des données. Modifiez le nom de l'axe des ordonnées (count -> Effectifs) et masquez la légende. Finalement, décrivez votre graphique en maximum 5 phrases. -->

```{r histo_fact}

```

<!--% À partir des 20 variables du jeu de données `zoo_sub`, réalisez et commentez deux nouveaux graphiques permettant d'analyser la distribution d'une variable. Utilisez deux géométries différentes et une variable facteur dans au moins un des deux graphiques. -->

```{r distrib1}

```

```{r distrib2}

```
